// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/annuel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/annuel">> = Specific
  const handler = {} as typeof import("../../app/annuel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cafe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cafe">> = Specific
  const handler = {} as typeof import("../../app/cafe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cloture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cloture">> = Specific
  const handler = {} as typeof import("../../app/cloture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/codir/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/codir">> = Specific
  const handler = {} as typeof import("../../app/codir/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/compte/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compte">> = Specific
  const handler = {} as typeof import("../../app/compte/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/conventions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/conventions/[id]">> = Specific
  const handler = {} as typeof import("../../app/conventions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/conventions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/conventions">> = Specific
  const handler = {} as typeof import("../../app/conventions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/edition/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/edition/[id]">> = Specific
  const handler = {} as typeof import("../../app/edition/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/financeurs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/financeurs/[id]">> = Specific
  const handler = {} as typeof import("../../app/financeurs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/financeurs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/financeurs">> = Specific
  const handler = {} as typeof import("../../app/financeurs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ma-semaine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ma-semaine">> = Specific
  const handler = {} as typeof import("../../app/ma-semaine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/portefeuille/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portefeuille">> = Specific
  const handler = {} as typeof import("../../app/portefeuille/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projets">> = Specific
  const handler = {} as typeof import("../../app/projets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/rappels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rappels">> = Specific
  const handler = {} as typeof import("../../app/rappels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seminaire/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seminaire">> = Specific
  const handler = {} as typeof import("../../app/seminaire/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/temps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/temps">> = Specific
  const handler = {} as typeof import("../../app/temps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/validations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/validations">> = Specific
  const handler = {} as typeof import("../../app/validations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/admin/export">> = Specific
  const handler = {} as typeof import("../../app/admin/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agenda/[token]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agenda/[token]">> = Specific
  const handler = {} as typeof import("../../app/api/agenda/[token]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pieces/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pieces/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/pieces/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cloture/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/cloture/export">> = Specific
  const handler = {} as typeof import("../../app/cloture/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/edition/[id]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/edition/[id]/export">> = Specific
  const handler = {} as typeof import("../../app/edition/[id]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
